version: "3.7"

services:
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app

#  selenium:
#    image: selenium/standalone-chrome
#    restart: always
#    ports:
#      - 4444:4444
#    shm_size: '2gb'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  telegram:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app
    command: ['poetry', 'run', 'python', '-m', 'bot']
